### ISSUE TITLE
Error 2000 After running ofx_create_new_usaa_bank_custom_profile.py

### ISSUE THREAD

**Issue by rjbarber** [yogi1967/MoneydancePythonScripts#16]
I've re-ran this 3 times. High confidence that I did everything correct. Cannot interpret the console messages beyond knowing I'm getting Error 2000 and Error 15500. I've double and triple checked the information from the USAA Quicken access page. I don't type anything, I copy/paste everything and ensure I don't have leading or trailing characters. Not sure what to do next. I'm hoping you have some bandwidth to devote to this and help me.
I don't have a VPN running and while I use cookie blocker extensions in the browser I use (Brave), I don't have any other form of web blocking going on that I'm aware of. Windows 10 OS. I don't believe it's possible for the web browser extensions to work outside of the web browser, but I'll be testing that to see if uninstalling all extensions helps. Low confidence it will help, but I'm trying anything at this point.
Internet Options are configured to accept session, first and third party cookies.
I can provide the console output outside of this forum if needed.

**Comment by yogi1967** [comment]
You’ll have to email me the console. Open console, keep it open. Do the download. Send me the output. 

...

**Comment by rjbarber** [comment]
Will do. Appreciate your time!

**Comment by yogi1967** [comment]
PS. Please confirm you’ve read version 8a of the PDF all the way through too?

**Comment by rjbarber** [comment]
I have read version 8a of the PDF all the way through. I'm pretty sure that is the version I used initially to do this for the first time ever today.

**Comment by yogi1967** [comment]
Where are we at with this now..? About 60+ other people have usaa working. Is yours?

**Comment by rjbarber** [comment]
It’s working by using hleOFXQuotes, but NOT from within Moneydance. 

 

I’ve tried everything I can think of and have spent a bunch of time redoing the script, trying with a different data file with only USAA. Still keep getting the Error 2000. 

 

At this point I’ve spent an unreasonable amount of time trying to get it to work, so I’m done. hleOFXQuotes will be what I use moving forward, until it doesn’t work any longer.

 

Thanks for the help and following up, but I’m done trying to get it to work.

 

Thank you,

RJ

**Comment by yogi1967** [comment]
Glad you have it working somehow. That’s the main concern.
