### ISSUE TITLE
extract_data -- nothing happens

### ISSUE THREAD

**Issue by markolbert** [yogi1967/MoneydancePythonScripts#17]
Thanx for writing and publishing these, as well as all the tips, etc!

I followed the instructions for installing extract_data on my Moneydance 2021 installation (Windows 10). At least I think I did. Only when I run the extension from within Moneydance nothing happens.

**Comment by markolbert** [comment]
Oops, never mind: turns out I missed the important caveat that I have to be running a preview version of MD for the scripts to work. My bad. I'll wait until they release the next version.

**Comment by yogi1967** [comment]
Just install MD2021 preview build 3066. It’s fine and is the bug fixed version of 2021.0(2006). This will likely become the ’stable’ version of MD2021.1… It’s the best and most stable version to be on.

**Comment by yogi1967** [comment]
PPS. If you don’t want to install the preview, just run the .py script in Moneybot.

**Comment by markolbert** [comment]
Cool, thanx!
