### ISSUE TITLE
Extract Data only exports some of my investment accounts

### ISSUE THREAD

**Issue by dandrake** [yogi1967/MoneydancePythonScripts#18]
I have three accounts with Betterment, but Extract Data for some reason will only extract data from one of them. I've set the "filter for accounts" to "ALL", but it only extracts data for one of the Betterment accounts.

I have a bunch of other accounts that all get extracted as expected.

Is there some kind of setup to the Moneydance account that's causing the extension to ignore these accounts? They are listed as investment accounts and appear to be configured just like the Betterment account that does get extracted.

**Comment by yogi1967** [comment]
Hi, So, which option in Extract_Data? Account registers or Investment Accounts?
Can you send me a screenshot of:
- The filters on my extension
- Your Tools>Accounts screen showing these accounts
?

**Comment by yogi1967** [comment]
Unzip this file and run the enclosed .py file (code) in Moneydance/Show Moneybot Console to diagnose your accounts....... Click Open, select this file, then RUN (not Run Snippet).

It's readonly, and safe..... Only you will see the output..

[find_accounts.py.zip](https://github.com/yogi1967/MoneydancePythonScripts/files/6951238/find_accounts.py.zip)

**Comment by dandrake** [comment]
Ah, I figured it out: I had some securities with a very, very small number of shares that the extension rounded to zero, and then crashed with a division by zero error.

This comes from weird rounding; my statements do some weird rounding and sometimes report a number of shares bought or sold that is simply wrong -- see [https://github.com/dandrake/betterment-pdf-to-qif](https://github.com/dandrake/betterment-pdf-to-qif). But even with increased precision, there's still some small error, and sometimes when entering a transaction that is supposed to sell all the shares in the account, it'll leave, say 0.000054 shares. 

The extension does some of its own rounding and in the errlog.txt file I see a line like this:

    extract_data.py(Extension):2021/08/14-16:42:59: Result of sumInfoBySecurity(book) self.QtyOfSharesTable:         {
    (...securities...) Security Name: 0L, (...securities...)}

and then

    extract_data.py(Extension):2021/08/14-15:15:56: Result of sumInfoBySecurity(book) self.moreCashBalanceAccounts:  {}
    Exception invoking python script: extract_data.py; actionType=menu
    Traceback (most recent call last):
      File "extension(extract_data):extract_data.py", line 5456, in <module>
      File "extension(extract_data):extract_data.py", line 5449, in run
      File "extension(extract_data):extract_data.py", line 5306, in do_stockglance2020
      File "extension(extract_data):extract_data.py", line 4960, in createAndShowGUI
      File "extension(extract_data):extract_data.py", line 4154, in getTableModel
    ZeroDivisionError: float division

When I fixed up the final sell transaction so that the number of shares in Moneydance was precisely zero, the extension worked fine.

When the divide by zero happens, it's very mysterious to the end user (as we see in this issue!). I would recommend somehow catching the error and at least throwing an error message popup; then it would at least give the user some idea of what went wrong and what might fix the problem.

**Comment by yogi1967** [comment]
Thanks for the details. Could you send me a ‘show transaction details’ output for the dodgy txns? Highlight in register and then right-click to get to the option. Or just screen show enough details for me to recreate. If I can recreate the data then I can easily fix the issue. I agree on the error trapping, but I still need to fix the issue. Thanks!!

**Comment by yogi1967** [comment]
PPS - have you tried the latest extract_data preview hosted here on GitHub? I ask as I have changed the rounding (for other reasons)?

**Comment by dandrake** [comment]
For the "show transaction details": there's no one specific transaction that causes this; rather, it's the accumulation of rounding errors that leave the security with a nonzero number of shares that somewhere gets rounded to zero.

I just reproduced the problem by adding a new security, setting the number of decimal places pretty high (6 or 7), and adding a buy transaction for 10 shares, and a sell for 9.999999 shares. I don't know all the details of the arithmetic handling in Moneydance or Python; I do have a math and software background and understand all the complexity and difficulty of floating point arithmetic, and financial transactions, and Decimal classes and all that quote-unquote fun stuff.

I haven't looked at the preview; I'll take a look. But just by creating a security with lots of decimal places, you can set up two transactions that leave Moneydance with a small number of shares and by fiddling with what "small" is, you can test the rounding.

**Comment by dandrake** [comment]
I tried the most recent preview (version 1013, I think) and I still get the error, with the same call stack as above.

**Comment by yogi1967** [comment]
I’ve found the errant code line. Thx.

**Comment by yogi1967** [comment]
The MD API is returning a cost_basis of zero in this situations and I am thus dividing by Zero (to calculate gain %). I now catch exception 'ZeroDivisionError' and store a result of zero (it occurs in about 6 places). I am also now trapping all errors with a nice user 'error' popup. Please could you try this version attached and verify it fixes the issue for you and that the results are still good?

unzip and get the enclosed mxt file. Ensure the name is exactly 'extract_data.mxt'. With MD open, double-click the mxt to install.

Let me know, thanks

[extract_data.zip](https://github.com/yogi1967/MoneydancePythonScripts/files/6988884/extract_data.zip)

**Comment by yogi1967** [comment]
Did the fix work?
