### ISSUE TITLE
Payees Listing

### ISSUE THREAD

**Issue by Koquillion** [yogi1967/MoneydancePythonScripts#19]
Recently discovered Toolbox which is really great.  Finally been able to delete a duplicate 'British Pound' currency I'd somehow created & was being mighty confusing.

One thing I would like to be able to do is produce a 'Payees' listing to check for near duplicates, mis-spelling etc etc which will have crept in over time. Is there a way of extracting this from the 'Description' field information?

**Comment by yogi1967** [comment]
I would say that would be easy. BUT I don’t really know what a payee is in ‘MD’ terms. Can you write the English logic?

**Comment by Koquillion** [comment]
A payee is the person, organisation or account that receives the payment. In Moneydance terms, it is the name in the Description field.

**Comment by yogi1967** [comment]
Perhaps the simplest route for now... Install my extract_data extension. Select the option 'Account Register Transactions'. This will dump your register to csv. Double-click to open in Excel. Do your filtering etc on the Description field in there.....?

**Comment by Koquillion** [comment]
Thanks for the suggestion. It worked well, and I was pleased to find there weren’t too many errors to correct.

Cheers
