### ISSUE TITLE
Future Reminders (request)

### ISSUE THREAD

**Issue by Kevin-N749** [yogi1967/MoneydancePythonScripts#20]
Hi Stuart,

I was wondering if it would be terribly difficult to have the future reminder extension follow the date format that is set in Preferences?

Currently the format of the extension is yyyy/MM/dd.  In 'the states' we're likely to use MM/dd/yyyy.

Thank you for your consideration.

-Kevin N. (not a member of MD support) : )

**Comment by yogi1967** [comment]
I’ve been waiting for that question.  😉. I’ll think about it. It’s actually a pain because of the sorting… but let’s see.

**Comment by Kevin-N749** [comment]
OK.  Thanks.  Don't put yourself out though; it's not a biggy. : )

**Comment by yogi1967** [comment]
Done and uploaded... Thx
