### ISSUE TITLE
Extract Data does not export Loan or Liability account transactions

### ISSUE THREAD

**Issue by mjtbiz** [yogi1967/MoneydancePythonScripts#21]
When I run the Extract Account register transactions function...

![image](https://user-images.githubusercontent.com/49888379/161443755-f64c42fc-cb48-46e3-841c-8774ecf3687e.png)

...wide open, with no filters...
![image](https://user-images.githubusercontent.com/49888379/161443736-65c003b2-6845-476c-99f5-f61ca9645816.png)

...none of the transactions associated with Loan or Liability accounts are exported--only Asset, Bank, and Credit card
![image](https://user-images.githubusercontent.com/49888379/161443854-e5d23ad0-8f66-45bc-8f0e-6ec704d63feb.png)

This is on MacOS...
![image](https://user-images.githubusercontent.com/49888379/161443917-df6301ef-869c-4ec2-b5a1-c196a7b175c8.png)

Running this version of MD...
![image](https://user-images.githubusercontent.com/49888379/161443928-c383e83d-5de0-4ee2-9c13-9e049883de0c.png)

And this version of Extract Data...
![image](https://user-images.githubusercontent.com/49888379/161443952-948db00a-4711-4835-9ad4-e7e2119231a5.png)

**Comment by yogi1967** [comment]
I’ll take a look. 

Regards Stuart

On 3 Apr 2022, at 20:07, Michael Thompson ***@***.***> wrote:

﻿
When I run the Extract Account register transactions function...



...wide open, with no filters...


...none of the transactions associated with Loan or Liability accounts are exported--only Asset, Bank, and Credit card


This is on MacOS...


Running this version of MD...


And this version of Extract Data...

**Comment by yogi1967** [comment]
You’re right. The code says:

if not (acct.getAccountType() == Account.AccountType.BANK
or acct.getAccountType() == Account.AccountType.CREDIT_CARD
or acct.getAccountType() == Account.AccountType.ASSET):
                                    return False

**Comment by yogi1967** [comment]
OK, I have now included LIABILITY & LOAN accounts. Latest uploaded here:
https://github.com/yogi1967/MoneydancePythonScripts/raw/master/extract_data.zip
Can you take a look and confirm? Thanks

**Comment by mjtbiz** [comment]
That works!  Thanks for the quick turnaround.  I have another enhancement that I will post under a different thread.
