### ISSUE TITLE
Option to Omit File and Parameter data from Export.

### ISSUE THREAD

**Issue by mjtbiz** [yogi1967/MoneydancePythonScripts#22]
First off, thanks so much for the Extract Data Extension for Moneydance--very useful!

I am using exported .csv file as an ODBC data source for reporting in Excel.  For whatever reason, the driver I am using does not properly recognize the last data row in the .csv file and does some funky stuff on the rows containing the file and parameter Information.  Might it be possible to have an option to NOT export these additional rows and ONLY include the data rows--something like this?

![image](https://user-images.githubusercontent.com/49888379/161454995-de6ccb73-d664-4397-8ee6-c0974f19db61.png)

**Comment by yogi1967** [comment]
Good idea and with a good reason... OK, I have now done this.. Please give it a try. Can you do me a favour and test all the extracts to ensure they all work (without crashing) on your setup.. I also found and fixed a tiny (new) bug, and also improved the Account Drop down list display. You can download latest from my site. Let me know? Thanks

**Comment by mjtbiz** [comment]
OK, I checked basic functionality with no parameters selected as follows:

- [x] StockGlance2020 with parameters -- no crash, file has parameters, display does not
- [x] StockGlance2020 without parameters -- no crash, file and display do not have parameters
- [x] Reminders with parameters -- no crash, file has parameters, display does not
- [x] Reminders without parameters -- no crash, file and display do not have parameters
- [x] Account register transactions with parameters -- no crash, file has parameters
- [x] Account register transactions without parameters -- no crash, file does not have parameters.
- [x] Investment transactions with parameters -- no crash, file has parameters.
- [x] Investment transactions without parameters -- no crash, file does not have parameters.
- [x] Currency price history with parameters -- no crash, file has parameters
- [x] Currency price history without parameters -- no crash, file does not have parameters

So it all checks out. Great job, thanks!

I did run into one other issue with the way I am using the data from the extracts.  I will post this as a new issue.

**Comment by yogi1967** [comment]
Thanks!
