### ISSUE TITLE
Problem with Lot Data in .csv file

### ISSUE THREAD

**Issue by mjtbiz** [yogi1967/MoneydancePythonScripts#23]
When extracting Investment Transactions the Lot Data column is structured as a subtable.  While I am sure that is useful for some applications, it creates cell data that can be very long.

![image](https://user-images.githubusercontent.com/49888379/161610524-a252cacb-485a-4873-ad9f-390dd595244e.png)

This creates a problem for me as I am using a SQLite compatible ODBC driver that only recognizes the first 8,000 characters in a cell.

Might it make sense to allow the user to omit this column as it can increase the file size and, as a subtable, is only useful in very specific use cases?  Another option is to put a limit on the character length of this value.

**Comment by yogi1967** [comment]
Done, enhancement made and uploaded. Please check it out and confirm. Thanks

**Comment by mjtbiz** [comment]
Works like a charm.  Thanks Stuart!  I assume all of the enhancements made this week will eventually make it into the current version, yes?

**Comment by yogi1967** [comment]
Email me on written_drizzle_0v@icloud.com and I'll email you back with my correct email address.

**Comment by yogi1967** [comment]
Yes, once IK sign them.. But I wait for a while to gather enough changes before submitting for signing...
