### ISSUE TITLE
Dialog cutoff or missing text in Edit/Setup (Multiple) Userids

### ISSUE THREAD

**Issue by tanderson1992** [yogi1967/MoneydancePythonScripts#26]
![image](https://user-images.githubusercontent.com/59940072/231253289-b5cedca7-2560-4e89-ab9a-d0b4082cc94c.png)

I guessed correctly that it was supposed to be IAGREE like the other prompts, but the text wasn't visible.

Toolbox v1058 and Moneydance Version / Build: 2023.2  Build: 5007

**Comment by yogi1967** [comment]
I just made a tweak.. It's a windows thing that truncates some messages (It's OK on Mac). Can you try latest preview and let me know if fixed? Thanks

**Comment by tanderson1992** [comment]
I tried and and got the same result. Just so you're sure I did it correctly, I uninstalled Toolbox from MD, downloaded your newest toolbox.zip from the code page that has the text about the tweak you made, manually installed the toolbox.mxt dated 12 April 2023, and restarted MD. The dialog is still cutoff and not resizable in Windows 11.

**Comment by yogi1967** [comment]
Hopefully fixed. Please grab latest build (from today) and try again - thanks!!

**Comment by tanderson1992** [comment]
I finally was able to try this, and it works. Thank you for the quick fix!

**Comment by yogi1967** [comment]
👍
