### ISSUE TITLE
Custom Balances: Does not display on Summary Page.

### ISSUE THREAD

**Issue by np6169** [yogi1967/MoneydancePythonScripts#32]
Moneydance V5141 - Displays correctly on Summary Screen.

Moneydance v5142
Installs via the Extension page but does not display. 
Not included on "Available Items" list in Settings/Summary Page

Moneydance v5146 - as above.

**Comment by yogi1967** [comment]
All extensions must be updated. Use the latest signed version from my page 
https://yogi1967.github.io/MoneydancePythonScripts/ 

Pls confirm ok?

**Comment by np6169** [comment]
Installed version (from Moneydance Extensions Page): Custom Balances v1051.

That is the same version from your 'signed versions' page.
I removed the Custom Balances Extension, re-downloaded v1051 from your site.
Custom Balances is still not available.

**Comment by yogi1967** [comment]
The latest is 1054. From this section

![image](https://github.com/user-attachments/assets/64b17568-f7b3-4be6-9bf2-ebaa75f80847)

It's net_account_balances

**Comment by np6169** [comment]
<img width="713" alt="Screenshot 2024-08-21 at 12 55 34" src="https://github.com/user-attachments/assets/efa85208-aa72-44bb-b88d-ad6b4a7aa7c9">

**Comment by yogi1967** [comment]
Yes. You have to rename it to just net_account_balances.mxt

(I wish IK would update their server!!)

**Comment by np6169** [comment]
<img width="754" alt="Screenshot 2024-08-21 at 13 16 11" src="https://github.com/user-attachments/assets/f7293eca-36fb-4dac-b242-9f2a5fc6bda0">

Sadly, still not showing on Summary Page and not an available item in Settings/Summary Page.
- deleted v1051
- restarted MD
- installed v1054
- retarted MD

**Comment by yogi1967** [comment]
Ok. Restart again. Grab help/show console. Send me the log. 

Email to:
...

**Comment by yogi1967** [comment]
Issue is resolved.
